# Generated by Django 3.1 on 2020-08-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESPdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.IntegerField(default=0)),
                ('umidita', models.IntegerField(default=0)),
                ('pressione', models.IntegerField(default=0)),
                ('pioggia', models.IntegerField(default=0)),
            ],
        ),
    ]
