# Generated by Django 3.1 on 2020-08-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelformsESPtesi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espdata',
            name='posizione',
            field=models.CharField(default='NEAR', max_length=30),
            preserve_default=False,
        ),
    ]
